// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksApp.DataAccess;

namespace TasksApp.DataAccess.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20210725102854_AuthorEntity")]
    partial class AuthorEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TasksApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Dinuwan Kalubowila"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Dureksha Wasala"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Chod Perera"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Chamika Visal"
                        });
                });

            modelBuilder.Entity("TasksApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2021, 7, 25, 15, 58, 54, 451, DateTimeKind.Local).AddTicks(8903),
                            Description = "Get books for school from DB",
                            Due = new DateTime(2021, 7, 30, 15, 58, 54, 453, DateTimeKind.Local).AddTicks(1173),
                            Status = 0,
                            Title = "Get Books"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Created = new DateTime(2021, 7, 25, 15, 58, 54, 453, DateTimeKind.Local).AddTicks(2315),
                            Description = "Get Medicine for sickness",
                            Due = new DateTime(2021, 7, 27, 15, 58, 54, 453, DateTimeKind.Local).AddTicks(2322),
                            Status = 1,
                            Title = "Get Medicine"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2021, 7, 25, 15, 58, 54, 453, DateTimeKind.Local).AddTicks(2331),
                            Description = "Get Foods from Resrurant",
                            Due = new DateTime(2021, 7, 28, 15, 58, 54, 453, DateTimeKind.Local).AddTicks(2332),
                            Status = 1,
                            Title = "Get Foods"
                        });
                });

            modelBuilder.Entity("TasksApp.Models.Todo", b =>
                {
                    b.HasOne("TasksApp.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
