// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksApp.DataAccess;

namespace TasksApp.DataAccess.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20210729114051_jobrole")]
    partial class jobrole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TasksApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddresNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("JobRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddresNo = "45",
                            City = "Colombo 1",
                            FullName = "Dinuwan Kalubowila",
                            JobRole = "Developer",
                            Street = "Street 1"
                        },
                        new
                        {
                            Id = 2,
                            AddresNo = "35",
                            City = "Colombo 2",
                            FullName = "Dureksha Wasala",
                            JobRole = "System Engineer",
                            Street = "Street 2"
                        },
                        new
                        {
                            Id = 3,
                            AddresNo = "25",
                            City = "Colombo 3",
                            FullName = "Chod Perera",
                            JobRole = "Developer",
                            Street = "Street 3"
                        },
                        new
                        {
                            Id = 4,
                            AddresNo = "15",
                            City = "Colombo 4",
                            FullName = "Chamika Visal",
                            JobRole = "QA",
                            Street = "Street 4"
                        });
                });

            modelBuilder.Entity("TasksApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2021, 7, 29, 17, 10, 50, 775, DateTimeKind.Local).AddTicks(2138),
                            Description = "Get books for school from DB",
                            Due = new DateTime(2021, 8, 3, 17, 10, 50, 776, DateTimeKind.Local).AddTicks(4661),
                            Status = 0,
                            Title = "Get Books"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Created = new DateTime(2021, 7, 29, 17, 10, 50, 776, DateTimeKind.Local).AddTicks(6276),
                            Description = "Get Medicine for sickness",
                            Due = new DateTime(2021, 7, 31, 17, 10, 50, 776, DateTimeKind.Local).AddTicks(6284),
                            Status = 1,
                            Title = "Get Medicine"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2021, 7, 29, 17, 10, 50, 776, DateTimeKind.Local).AddTicks(6294),
                            Description = "Get Foods from Resrurant",
                            Due = new DateTime(2021, 8, 1, 17, 10, 50, 776, DateTimeKind.Local).AddTicks(6296),
                            Status = 1,
                            Title = "Get Foods"
                        });
                });

            modelBuilder.Entity("TasksApp.Models.Todo", b =>
                {
                    b.HasOne("TasksApp.Models.Author", "Author")
                        .WithMany("Todos")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TasksApp.Models.Author", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
